version: "3"
services:
  slicer_1:
    build:
      context: ./slicer
    environment:
      - VNC_PASSWORD=vncpassword@123
    volumes:
      - ./data/slicer:/root/data/
      - ./data/annotations/user_1:/root/annotations/
    ports:
      - 5900:5900
    tty: true
    restart: on-failure
  slicer_2:
    build:
      context: ./slicer
    environment:
      - VNC_PASSWORD=vncpassword@123
    volumes:
      - ./data/slicer:/root/data/
      - ./data/annotations/user_2:/root/annotations/
    ports:
      - 5901:5900
    tty: true
    restart: on-failure
  slicer_3:
    build:
      context: ./slicer
    environment:
      - VNC_PASSWORD=vncpassword@123
    volumes:
      - ./data/slicer:/root/data/
      - ./data/annotations/user_3:/root/annotations/
    ports:
      - 5902:5900
    tty: true
    restart: on-failure
  slicer_4:
    build:
      context: ./slicer
    environment:
      - VNC_PASSWORD=vncpassword@123
    volumes:
      - ./data/slicer:/root/data/
      - ./data/annotations/user_4:/root/annotations/
    ports:
      - 5903:5900
    tty: true
    restart: on-failure
  portal-client:
    build:
      context: ./portal/client
  portal-server:
    build:
      context: ./portal/server
    env_file:
      - ./portal/server/.env
  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017
    env_file:
      - ./portal/server/.env
    volumes:
      - ./data/db:/data/db
  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
