version: "3"
services:
  slicer:
    build:
      context: ./slicer
      args:
        VNC_PASSWORD: "vncpassword@123"
    volumes:
      - ./data/slicer:/root/data/
      - ./data/annotations:/root/annotations/
    ports:
      - 5900:5900
    tty: true
    restart: on-failure
  portal-client:
    build:
      context: ./portal/client
  portal-server:
    build:
      context: ./portal/server
  mongodb:
    image: mongo:4.0
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
